services:
  db:
    image: postgres:17
    container_name: memento-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: memento
      POSTGRES_PASSWORD: memento
      POSTGRES_DB: memento

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: